name: Skintool
version: ${project.version}
main: me.tippie.skintool.SkinTool
api-version: 1.13
authors: [ Tippie ]
description: Basic tool that sets skins
commands:
  saveskin:
    description: saves a skin to the local plugin storage (doesn't save on restart YET)
  setskin:
    description: sets a skin from the local plugin storage
